import { useCallback, useEffect, useState } from "react";
import type { ClineChatActionResult } from "@/hooks/use-cline-chat-runtime-actions";
import type { RuntimeTaskChatMessage, RuntimeTaskImage, RuntimeTaskSessionMode } from "@/runtime/types";
export type PrimeAcpChatMessage = RuntimeTaskChatMessage;
interface UsePrimeAcpChatSessionInput { taskId: string; onSendMessage?: (taskId: string, text: string, options?: { mode?: RuntimeTaskSessionMode; images?: RuntimeTaskImage[] }) => Promise<ClineChatActionResult>; onCancelTurn?: (taskId: string) => Promise<{ ok: boolean; message?: string }>; onLoadMessages?: (taskId: string) => Promise<PrimeAcpChatMessage[] | null>; incomingMessages?: PrimeAcpChatMessage[] | null; incomingMessage?: PrimeAcpChatMessage | null; }
function areEqual(a: PrimeAcpChatMessage, b: PrimeAcpChatMessage): boolean { return a.content === b.content && a.role === b.role && a.createdAt === b.createdAt && JSON.stringify(a.meta ?? null) === JSON.stringify(b.meta ?? null); }
function upsert(list: PrimeAcpChatMessage[], next: PrimeAcpChatMessage): PrimeAcpChatMessage[] { const idx = list.findIndex((m) => m.id === next.id); if (idx < 0) return [...list, next]; const cur = list[idx]; if (!cur || areEqual(cur, next)) return list; const copy = [...list]; copy[idx] = next; return copy; }
function merge(base: PrimeAcpChatMessage[], add: PrimeAcpChatMessage[]): PrimeAcpChatMessage[] { return add.reduce((acc, m) => upsert(acc, m), [...base]); }
export function usePrimeAcpChatSession({ taskId, onSendMessage, onCancelTurn, onLoadMessages, incomingMessages = null, incomingMessage = null }: UsePrimeAcpChatSessionInput) {
  const [messages, setMessages] = useState<PrimeAcpChatMessage[]>([]); const [isSending, setIsSending] = useState(false); const [isCanceling, setIsCanceling] = useState(false); const [isLoading, setIsLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { setMessages([]); setError(null); }, [taskId]);
  useEffect(() => { if (!onLoadMessages) { setMessages([]); return; } setError(null); let cancelled = false; setIsLoading(true); void onLoadMessages(taskId).then((loaded) => { if (cancelled) return; setMessages((cur) => merge(loaded ?? [], cur)); }).catch((e) => { if (cancelled) return; setError(e instanceof Error ? e.message : String(e)); }).finally(() => { if (!cancelled) setIsLoading(false); }); return () => { cancelled = true; }; }, [onLoadMessages, taskId]);
  useEffect(() => { if (incomingMessages === null) return; if (incomingMessages.length === 0) { setMessages([]); return; } setMessages((cur) => merge(cur, incomingMessages)); }, [incomingMessages]);
  useEffect(() => { if (!incomingMessage) return; setMessages((cur) => upsert(cur, incomingMessage)); }, [incomingMessage]);
  const cancelTurn = useCallback(async (): Promise<boolean> => { if (!onCancelTurn || isCanceling) return false; setError(null); setIsCanceling(true); try { const res = await onCancelTurn(taskId); if (!res.ok) { setError(res.message ?? "Could not cancel turn."); return false; } return true; } catch (e) { setError(e instanceof Error ? e.message : String(e)); return false; } finally { setIsCanceling(false); } }, [isCanceling, onCancelTurn, taskId]);
  const sendMessage = useCallback(async (text: string, options?: { mode?: RuntimeTaskSessionMode; images?: RuntimeTaskImage[] }): Promise<boolean> => { const trimmed = text.trim(); const hasImages = Boolean(options?.images && options.images.length > 0); if ((!trimmed && !hasImages) || !onSendMessage) return false; setError(null); setIsSending(true); try { const result = options ? await onSendMessage(taskId, trimmed, options) : await onSendMessage(taskId, trimmed); if (!result.ok) { setError(result.message ?? "Could not send message."); return false; } const sent = result.chatMessage ?? null; if (sent) setMessages((cur) => upsert(cur, sent)); else if (onLoadMessages) { const loaded = await onLoadMessages(taskId); setMessages(loaded ?? []); } return true; } catch (e) { setError(e instanceof Error ? e.message : String(e)); return false; } finally { setIsSending(false); } }, [onLoadMessages, onSendMessage, taskId]);
  return { messages, isSending: isSending || isLoading, isCanceling, error, sendMessage, cancelTurn };
}
